# Generated by Django 4.2.5 on 2023-09-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=255, verbose_name="Ім'я")),
                ('last_name', models.CharField(default='', max_length=255, verbose_name='Прізвище')),
                ('age', models.IntegerField(default='', verbose_name='Вік')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенти',
            },
        ),
    ]
